robot_cfg:
  kinematics:
    use_usd_kinematics: False
    urdf_path: "robot/aloha/aloha_v1.urdf"
    asset_root_path: "robot/aloha/meshes"
    usd_robot_root: "/aloha_v1"
    base_link: "map"
    ee_link: "vx300s_left_right_finger_link"
    link_names:
      [
        "vx300s_left_right_finger_link",   # 左アームEE
        "vx300s_right_right_finger_link"   # 右アームEE
      ]
    collision_link_names:
      [
        # static environment (optional):
        "jigu",
        "mount",
        "pole",
        "table",

        # left arm
        "vx300s_left_base",
        "vx300s_left_shoulder_link",
        "vx300s_left_upper_arm_link",
        "vx300s_left_upper_forearm_link",
        "vx300s_left_lower_forearm_link",
        "vx300s_left_wrist_link",
        "vx300s_left_gripper_link",
        "vx300s_left_gripper_prop_link",
        "vx300s_left_left_finger_link",
        "vx300s_left_right_finger_link",

        # right arm
        "vx300s_right_base",
        "vx300s_right_shoulder_link",
        "vx300s_right_upper_arm_link",
        "vx300s_right_upper_forearm_link",
        "vx300s_right_lower_forearm_link",
        "vx300s_right_wrist_link",
        "vx300s_right_gripper_link",
        "vx300s_right_gripper_prop_link",
        "vx300s_right_left_finger_link",
        "vx300s_right_right_finger_link",

        "charuco_dmy_link",
      ]

    collision_spheres: "spheres/aloha_v1.yml"

    collision_sphere_buffer: 0.005

    self_collision_ignore:
      {
        "vx300s_left_shoulder_link": ["vx300s_left_upper_arm_link"],
        "vx300s_left_upper_arm_link": ["vx300s_left_upper_forearm_link"],
        "vx300s_left_upper_forearm_link": ["vx300s_left_lower_forearm_link"],
        "vx300s_left_lower_forearm_link": ["vx300s_left_wrist_link"],
        "vx300s_right_shoulder_link": ["vx300s_right_upper_arm_link"],
        "vx300s_right_upper_arm_link": ["vx300s_right_upper_forearm_link"],
        "vx300s_right_upper_forearm_link": ["vx300s_right_lower_forearm_link"],
        "vx300s_right_lower_forearm_link": ["vx300s_right_wrist_link"],
        "vx300s_left_gripper_link": ["vx300s_left_left_finger_link", "vx300s_left_right_finger_link"],
        "vx300s_right_gripper_link": ["vx300s_right_left_finger_link", "vx300s_right_right_finger_link"],
      }

    self_collision_buffer:
      {
        "vx300s_left_base": 0.005,
        "vx300s_right_base": 0.005,
      }

    mesh_link_names:
      [
        "jigu",
        "mount",
        "pole",
        "table",
        "vx300s_left_base",
        "vx300s_left_shoulder_link",
        "vx300s_right_right_finger_link"
      ]

    lock_joints:
      {
        "vx300s_left_gripper": 0.0,
        "vx300s_right_gripper": 0.0
      }
    cspace:
      joint_names:
        [
          "vx300s_left_waist",
          "vx300s_left_shoulder",
          "vx300s_left_elbow",
          "vx300s_left_forearm_roll",
          "vx300s_left_wrist_angle",
          "vx300s_left_wrist_rotate",
          "vx300s_left_left_finger",

          "vx300s_right_waist",
          "vx300s_right_shoulder",
          "vx300s_right_elbow",
          "vx300s_right_forearm_roll",
          "vx300s_right_wrist_angle",
          "vx300s_right_wrist_rotate",
          "vx300s_right_left_finger",
        ]
      retract_config:
        [
          0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,  # left
          0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1  # right
        ]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 15.0
