robot_cfg:
  kinematics:
    use_usd_kinematics: False
    urdf_path: "robot/aloha/aloha_v1_2arm.urdf"
    asset_root_path: "robot/aloha/meshes"
    usd_robot_root: "bimanual_viperx_transfer_cube"
    base_link: "base_link"
    ee_link: "vx300s_left_gripper_link"
    link_names:
      [
        "vx300s_left_gripper_link",
        "vx300s_right_gripper_link"
      ]
    collision_link_names:
        - "vx300s_left_base"
        - "vx300s_left_shoulder_link"
        - "vx300s_left_upper_arm_link"
        - "vx300s_left_upper_forearm_link"
        - "vx300s_left_lower_forearm_link"
        - "vx300s_left_wrist_link"
        - "vx300s_left_gripper_link"
        - "vx300s_right_base"
        - "vx300s_right_shoulder_link"
        - "vx300s_right_upper_arm_link"
        - "vx300s_right_upper_forearm_link"
        - "vx300s_right_lower_forearm_link"
        - "vx300s_right_wrist_link"
        - "vx300s_right_gripper_link"

    collision_spheres: "spheres/aloha_v1_2arm.yml"

    collision_sphere_buffer: 0.005

    self_collision_ignore:
      {
        "vx300s_left_shoulder_link": ["vx300s_left_upper_arm_link"],
        "vx300s_left_upper_arm_link": ["vx300s_left_upper_forearm_link"],
        "vx300s_left_upper_forearm_link": ["vx300s_left_lower_forearm_link"],
        "vx300s_left_lower_forearm_link": ["vx300s_left_wrist_link"],
        "vx300s_right_shoulder_link": ["vx300s_right_upper_arm_link"],
        "vx300s_right_upper_arm_link": ["vx300s_right_upper_forearm_link"],
        "vx300s_right_upper_forearm_link": ["vx300s_right_lower_forearm_link"],
        "vx300s_right_lower_forearm_link": ["vx300s_right_wrist_link"]
      }

    self_collision_buffer:
      vx300s_left_base: 0.01
      vx300s_left_shoulder_link: 0.01
      vx300s_left_upper_arm_link: 0.01
      vx300s_left_upper_forearm_link: 0.01
      vx300s_left_lower_forearm_link: 0.01
      vx300s_left_wrist_link: 0.01
      vx300s_left_gripper_link: 0.01
      vx300s_right_base: 0.01
      vx300s_right_shoulder_link: 0.01
      vx300s_right_upper_arm_link: 0.01
      vx300s_right_upper_forearm_link: 0.01
      vx300s_right_lower_forearm_link: 0.01
      vx300s_right_wrist_link: 0.01
      vx300s_right_gripper_link: 0.01

    mesh_link_names:
      - "vx300s_left_base"
      - "vx300s_left_shoulder_link"
      - "vx300s_left_upper_arm_link"
      - "vx300s_left_upper_forearm_link"
      - "vx300s_left_lower_forearm_link"
      - "vx300s_left_wrist_link"
      - "vx300s_left_gripper_link"
      - "vx300s_right_base"
      - "vx300s_right_shoulder_link"
      - "vx300s_right_upper_arm_link"
      - "vx300s_right_upper_forearm_link"
      - "vx300s_right_lower_forearm_link"
      - "vx300s_right_wrist_link"
      - "vx300s_right_gripper_link"

    cspace:
      joint_names:
        - "vx300s_left_waist"
        - "vx300s_left_shoulder"
        - "vx300s_left_elbow"
        - "vx300s_left_forearm_roll"
        - "vx300s_left_wrist_angle"
        - "vx300s_left_wrist_rotate"
        - "vx300s_left_gripper"
        - "vx300s_right_waist"
        - "vx300s_right_shoulder"
        - "vx300s_right_elbow"
        - "vx300s_right_forearm_roll"
        - "vx300s_right_wrist_angle"
        - "vx300s_right_wrist_rotate"
        - "vx300s_right_gripper"

      retract_config:
        - -0.1
        - -0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.0
        - 0.0
        - -0.1
        - -0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.0
        - 0.0
      
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 15.0
