robot_cfg:
  kinematics:
    use_usd_kinematics: False

    urdf_path: "robot/aloha/aloha_v1_1arm.urdf"
    asset_root_path: "robot/aloha/meshes"

    usd_robot_root: "bimanual_viperx_transfer_cube"

    base_link: "base_link"
    ee_link: "vx300s_left_left_finger_link"


    link_names:
      [
        "vx300s_left_base",
        "vx300s_left_shoulder_link",
        "vx300s_left_upper_arm_link",
        "vx300s_left_upper_forearm_link",
        "vx300s_left_lower_forearm_link",
        "vx300s_left_wrist_link",
        "vx300s_left_gripper_link",
        "vx300s_left_gripper_prop_link",
        "vx300s_left_left_finger_link",
        "vx300s_left_right_finger_link"
      ]

    collision_link_names:
      [
        "vx300s_left_base",
        "vx300s_left_shoulder_link",
        "vx300s_left_upper_arm_link",
        "vx300s_left_upper_forearm_link",
        "vx300s_left_lower_forearm_link",
        "vx300s_left_wrist_link",
        "vx300s_left_gripper_link",
        "vx300s_left_gripper_prop_link",
        "vx300s_left_left_finger_link",
        "vx300s_left_right_finger_link"
      ]

    collision_spheres: "spheres/aloha_v1_1arm.yml"
    collision_sphere_buffer: 0.001

    self_collision_ignore:
      {
        "vx300s_left_shoulder_link": ["vx300s_left_upper_arm_link"],
        "vx300s_left_upper_arm_link": ["vx300s_left_upper_forearm_link"],
        "vx300s_left_upper_forearm_link": ["vx300s_left_lower_forearm_link"],
        "vx300s_left_lower_forearm_link": ["vx300s_left_wrist_link"],
        "vx300s_left_gripper_link": ["vx300s_left_left_finger_link", "vx300s_left_right_finger_link"],
      }

    self_collision_buffer:
      {
        "vx300s_left_base": 0.01,
      }

    mesh_link_names:
      [
        "vx300s_left_base",
        "vx300s_left_shoulder_link",
        "vx300s_left_right_finger_link"
      ]

    lock_joints:
      {
        "vx300s_left_gripper": 0.0
      }

    cspace:
      joint_names:
        [
          "vx300s_left_waist",
          "vx300s_left_shoulder",
          "vx300s_left_elbow",
          "vx300s_left_forearm_roll",
          "vx300s_left_wrist_angle",
          "vx300s_left_wrist_rotate",
          "vx300s_left_left_finger"
        ]

      retract_config:
        [
          0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.03
        ]
      null_space_weight:       [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 15.0
