robot: "aloha_v1_2arm"

collision_spheres:
  vx300s_left_base:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_left_shoulder_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_left_upper_arm_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_left_upper_forearm_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_left_lower_forearm_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_left_wrist_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_left_gripper_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_right_base:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_right_shoulder_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_right_upper_arm_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_right_upper_forearm_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_right_lower_forearm_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_right_wrist_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01

  vx300s_right_gripper_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.01
