##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
collision_spheres:
    panda_link0:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01 #0.07
    panda_link1:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    panda_link2:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    panda_link3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    panda_link4:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    panda_link5:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    panda_link6:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01 
    panda_link7:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    panda_hand:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    panda_leftfinger:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01 
    panda_rightfinger:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01